#
# _config.yml for Team484
#

exclude: [ "README.md", "LICENSE", "*.sh", "**/*_src*" ]
permalink: /notes/:year/:month/:day/:title.html
production_url: http://reference.team484.org
title : FRC Team 484 Documentation Site

theme: jekyll-theme-minimal